
DROP TABLE IF EXISTS schema_version;
DROP TABLE IF EXISTS node_runs CASCADE;
DROP TABLE IF EXISTS runs CASCADE;
DROP TABLE IF EXISTS edges CASCADE;
DROP TABLE IF EXISTS nodes CASCADE;
DROP TABLE IF EXISTS jobs CASCADE;
